env_prefix     = "dev"
vpc_cidr_block = "10.10.0.0/16"
web_subnet     = "10.10.1.0/24"
region         = "us-east-1"
subnet_zone    = "us-east-1a"
instance_type  = "t2.micro"
ssh_key_name   = "TF_SSH_Key"
